# DIAGNOSTICKÁ MATICE – RYBA

## Jak podle odpovědí týmu poznat převažující dysfunkci?

| Převládající úhel | Týmová diagnóza | Okamžitá intervence |
|-------------------|-----------------|---------------------|
| **1. Vibrační komunikace** | Tým komunikuje pouze slovy, ignoruje atmosféru, energii, neverbální signály. Řeší se, co je „řečeno“, ne co je „cítěno“. | Zavést [**čtení vibrací**](./kreativni_mod.md#1-protílek-na-vibrační-komunikaci–čtení-vibrací): 2 minuty na popis „jak se dnes cítí voda“. |
| **2. Systemický dopad** | Schůze jsou vnímány jako nutné zlo k předání informací, ne jako příležitost změnit kulturu. Výstupem je zápis, ne vlnění. | Měřit úspěch komunikace otázkou: [**„Jak se změnilo naše prostředí?“**](./kreativni_mod.md#2-protílek-na-systemický-dopad–změna-prostředí) |
| **3. Přesnost před hlasitostí** | Hlasití a sebevědomí jedinci přehlušují ty s přesnými, ale tichými postřehy. Diskuse je soutěž v rétorice. | Zavést pravidlo [**váhy slova**](./kreativni_mod.md#3-protílek-na-přesnost-před-hlasitostí–váha-slova) – omezený počet promluv, oceňovat přesnost. |
| **4. Různorodé žánry** | Kultura vyžaduje jednotný styl komunikace (korporátní mluvu). Lidé se nemohou vyjádřit svým přirozeným „hudebním druhem“. | Vytvořit [**hudební mapu týmu**](./kreativni_mod.md#4-protílek-na-různorodé-žánry–hudební-mapa) a ocenit diverzitu projevů. |
| **5. Ptačí křikot** | Komunikace je plná prázdných frází, bezduchých reportů a opakování hesel. Je hlasitá, ale nic neříká. | Provést [**audit ptačího křiku**](./kreativni_mod.md#5-protílek-na-ptačí-křikot–audit-křikotu) – identifikovat 3 nejprázdnější fráze a eliminovat je. |
| **6. Mlčení jako mocná dovednost** | Ticho je považováno za nepohodlné, neproduktivní. Pauzy se okamžitě zaplňují slovy. Chybí produktivní ticho. | Zavést [**rybí pauzy**](./kreativni_mod.md#6-protílek-na-mlčení-jako-mocnou-dovednost–rybí-pauzy) – 1–2 minuty povinného ticha na reflexi. |
| **7. Komunikace s prostředím** | Prezentace směřují nahoru (k šéfovi) nebo ven (ke klientovi), ale málokdy dovnitř, k systému týmu. Chybí dialog s vlastním ekosystémem. | Před každou komunikací se ptát: [**„Mluvím ke týmu, nebo pro systém?“**](./kreativni_mod.md#7-protílek-na-komunikaci-s-prostředím–mluvit-pro-systém) |
| **8. Ticho, které nese obsah** | Tišší členové jsou považováni za pasivní. Systém neumí číst jejich „tichý rap“ – práci, pozorování, vliv. | Vytvořit mechanismy pro [**zviditelnění ticha**](./kreativni_mod.md#8-protílek-na-ticho-které-nese-obsah–zviditelnit-ticho) (psané reflexe, brainwriting). |
| **9. Beaty, které tvoří prostředí** | Komunikace je oddělena od práce („vezmeme to offline“). Ztrácí se přirozený rytmus a kontext. | Integrovat komunikaci do [**proudů práce**](./kreativni_mod.md#9-protílek-na-beaty-které-tvoří-prostředí–komunikace-v-proudu) – místo meetingů async updates. |
| **10. Vnímání místo poslouchání** | Úspěch komunikace se hodnotí jen podle toho, co bylo řečeno, ne podle atmosféry, pocitů, důsledků. | Po setkáních se ptát: [**„Co jsi pocítil? Co nebylo řečeno?“**](./kreativni_mod.md#10-protílek-na-vnímání-místo-poslouchání–vnímat-ne-poslouchat) |
| **11. Autentické vyjádření** | Lidé jsou nuceni hrát role nebo používat jazyk, který není jejich přirozený. To plodí frustraci a neautenticitu. | Identifikovat [**komunikační žánry**](./kreativni_mod.md#11-protílek-na-autentické-vyjádření–komunikační-žánr) a hledat, jak je integrovat do společného orchestru. |
| **12. Neviditelné vítězství** | Tým oslavuje jen viditelné úspěchy, přehlíží tiché systémové výhry (důvěra, vyřešený konflikt, stabilita). | Zavést [**hitparádu pod hladinou**](./kreativni_mod.md#12-protílek-na-neviditelné-vítězství–hitparáda-pod-hladinou) – oceňovat neviditelné úspěchy. |
